/**
 * Embedded sandbox worker assets.
 *
 * Each `with { type: "file" }` import tells `bun build --compile` to embed
 * the referenced file into the binary. At runtime the imported value is a
 * string path into Bun's virtual filesystem (`/$bunfs/root/<name>-<hash>.<ext>`),
 * readable via `node:fs` but not directly usable for Worker-adjacent paths
 * (see `materialize.ts` for why).
 *
 * The files themselves are staged by `scripts/build-sandbox-runtime.ts`,
 * which copies them out of `just-bash`'s node_modules before the main
 * compile step runs. If you see a missing-module error importing anything
 * from `./_runtime/`, run that script first.
 */

/// <reference path="./runtime-assets.d.ts" />

import qjsWasm from "../_runtime/emscripten-module.wasm" with { type: "file" };
import manifest from "../_runtime/manifest.json" with { type: "json" };
import pythonCjs from "../_runtime/python.cjs" with { type: "file" };
import pythonWasm from "../_runtime/python.wasm" with { type: "file" };
import pythonStdlib from "../_runtime/python313.zip" with { type: "file" };
import jsExecWorker from "../_runtime/worker-js-exec.js" with { type: "file" };
import pythonWorker from "../_runtime/worker-python.js" with { type: "file" };

export interface EmbeddedAssets {
	/** Absolute paths into Bun's virtual FS; readable via node:fs. */
	readonly paths: {
		readonly pythonWorker: string;
		readonly pythonCjs: string;
		readonly pythonWasm: string;
		readonly pythonStdlib: string;
		readonly jsExecWorker: string;
		readonly qjsWasm: string;
	};
	/**
	 * Short content hash over all embedded assets, used to key the
	 * on-disk materialization directory. Regenerated by the build script
	 * whenever any asset changes.
	 */
	readonly hash: string;
}

export const embeddedAssets: EmbeddedAssets = {
	paths: {
		pythonWorker,
		pythonCjs,
		pythonWasm,
		pythonStdlib,
		jsExecWorker,
		qjsWasm,
	},
	hash: manifest.hash,
};
