/**
 * Ambient module declarations for sandbox runtime assets.
 *
 * The files under `./_runtime/` are staged by
 * `scripts/build-sandbox-runtime.ts` at build-time and gitignored. They
 * aren't present on a fresh clone, which makes TypeScript unable to
 * resolve the `import ... from "./_runtime/..."` statements in
 * `assets.ts`. These ambient declarations give the compiler a stable
 * type for each extension without requiring the files to exist on disk.
 *
 * Runtime behaviour is independent of these types: at runtime the
 * imports are supplied by `bun build --compile`'s asset embedding, not
 * by the TypeScript resolver.
 */

declare module "*.wasm" {
	/** Path into Bun's virtual embedded filesystem. */
	const path: string;
	export default path;
}

declare module "*.cjs" {
	/** Path into Bun's virtual embedded filesystem. */
	const path: string;
	export default path;
}

declare module "*.zip" {
	/** Path into Bun's virtual embedded filesystem. */
	const path: string;
	export default path;
}

declare module "../_runtime/worker-python.js" {
	/** Path into Bun's virtual embedded filesystem. */
	const path: string;
	export default path;
}

declare module "../_runtime/worker-js-exec.js" {
	/** Path into Bun's virtual embedded filesystem. */
	const path: string;
	export default path;
}

// Also match when the compiler resolves the ambient module through the
// on-disk staged file (it prefers the real file over a path-literal
// ambient declaration when the file exists). A wildcard pattern with
// `.js` extension covers both worker files.
declare module "*/_runtime/worker-python.js" {
	const path: string;
	export default path;
}

declare module "*/_runtime/worker-js-exec.js" {
	const path: string;
	export default path;
}

declare module "../_runtime/manifest.json" {
	/**
	 * Content-hash manifest generated by
	 * scripts/build-sandbox-runtime.ts. The shape intentionally differs
	 * from the richer in-memory manifest the script returns — only the
	 * fields the runtime reads are declared here.
	 */
	export const hash: string;
}
