// Type stub for the auto-generated embedded-assets module.
// The actual file (embedded-assets.ts) is generated by scripts/embed-assets.ts
// and is gitignored. This stub satisfies TypeScript module resolution in CI
// where the generated file is absent.

export interface EmbeddedAsset {
	content: string;
	contentType: string;
}

export declare const embeddedAssets: Map<string, EmbeddedAsset> | undefined;
