#!/usr/bin/env bun
/**
 * Reads built web assets from packages/web/dist/client/ and generates
 * a TypeScript module that embeds them as strings, so bun build --compile
 * can include them in the single binary.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, extname, resolve, dirname } from "node:path";

// Resolve paths relative to this script, not cwd
const SCRIPT_DIR = dirname(new URL(import.meta.url).pathname);
const ROOT = resolve(SCRIPT_DIR, "..");
const DIST_DIR = join(ROOT, "packages/web/dist/client");
const OUTPUT = join(ROOT, "packages/web/src/server/embedded-assets.ts");

interface Asset {
	path: string; // URL path like "/index.html" or "/assets/index-abc.js"
	content: string;
	contentType: string;
}

function getMimeType(filename: string): string {
	const ext = extname(filename);
	const mimes: Record<string, string> = {
		".html": "text/html; charset=utf-8",
		".js": "application/javascript; charset=utf-8",
		".css": "text/css; charset=utf-8",
		".svg": "image/svg+xml",
		".json": "application/json",
		".png": "image/png",
		".ico": "image/x-icon",
	};
	return mimes[ext] || "application/octet-stream";
}

function collectAssets(dir: string, prefix = ""): Asset[] {
	const assets: Asset[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const fullPath = join(dir, entry.name);
		const urlPath = `${prefix}/${entry.name}`;
		if (entry.isDirectory()) {
			assets.push(...collectAssets(fullPath, urlPath));
		} else {
			assets.push({
				path: urlPath,
				content: readFileSync(fullPath, "utf-8"),
				contentType: getMimeType(entry.name),
			});
		}
	}
	return assets;
}

const assets = collectAssets(DIST_DIR);

const lines = [
	"// Auto-generated by scripts/embed-assets.ts — do not edit",
	"// Embeds web UI assets for single-binary distribution",
	"",
	"export interface EmbeddedAsset {",
	"\tcontent: string;",
	"\tcontentType: string;",
	"}",
	"",
	"export const embeddedAssets = new Map<string, EmbeddedAsset>([",
];

for (const asset of assets) {
	const escaped = JSON.stringify(asset.content);
	lines.push(`\t[${JSON.stringify(asset.path)}, { content: ${escaped}, contentType: ${JSON.stringify(asset.contentType)} }],`);
}

lines.push("]);");
lines.push("");

writeFileSync(OUTPUT, lines.join("\n"));
console.log(`Embedded ${assets.length} assets into ${OUTPUT}`);
