#!/usr/bin/env bun
// Generate build-info.ts with git commit hash and build timestamp
// Run during build process before binary compilation

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

function getGitCommitHash(): string {
	try {
		const hash = execSync("git rev-parse --short HEAD", {
			encoding: "utf-8",
			stdio: ["pipe", "pipe", "ignore"],
		}).trim();
		return hash;
	} catch {
		return "unknown";
	}
}

function getBuildTimestamp(): string {
	return new Date().toISOString();
}

function generateBuildInfo() {
	const commitHash = getGitCommitHash();
	const buildTime = getBuildTimestamp();

	const content = `// Auto-generated by scripts/generate-build-info.ts
// DO NOT EDIT MANUALLY

export const COMMIT_HASH = "${commitHash}";
export const BUILD_TIME = "${buildTime}";
`;

	const outPath = resolve("packages/cli/src/build-info.ts");
	writeFileSync(outPath, content, "utf-8");

	console.log(`Generated build info: commit ${commitHash}, built ${buildTime}`);
}

generateBuildInfo();
